import { ComposeService } from "@dappnode/types";

export const composeSafeKeys: (keyof ComposeService)[] = [
  "cap_add",
  "cap_drop",
  "command",
  "depends_on",
  "devices",
  "entrypoint",
  "environment",
  "expose",
  "extra_hosts",
  "healthcheck",
  "labels",
  "logging",
  "network_mode",
  "networks",
  "ports",
  "privileged",
  "restart",
  "stop_grace_period",
  "stop_signal",
  "user",
  "volumes",
  "working_dir",
  "security_opt",
  "image",
  "build",
  "volumes",
  "environment",
  "pid",
  "container_name",
  "dns",
  "ulimits",
  "deploy"
];
